apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bankapps
spec:
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              bankapps: 'enabled'
      - git:
          repoURL: https://github.com/dhpup/appset-rollouts-v2.git
          revision: livestream
          directories:
          - path: clusters/bankapps/*
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
          - key: app
            operator: In
            values:
              - argo-rollouts
        - matchExpressions:
          - key: app
            operator: NotIn
            values:
              - argo-rollouts
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
      annotations:
        notifications.argoproj.io/subscribe.slack: test-dan
      labels:
        app: '{{path.basename}}'
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: '{{server}}'
      source:
        repoURL: https://github.com/dhpup/appset-rollouts-v2.git
        targetRevision: livestream
        path: '{{path}}'
      project: bankapps
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
